// 'use client'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
// import { Analytics } from '@vercel/analytics/react';
// import { SpeedInsights } from "@vercel/speed-insights/next"
const inter = Inter({ 
  subsets: ['latin'] ,
  variable: '--font-inter'})

export const metadata: Metadata = {
  title: 'Shobhnik',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        {/* <SpeedInsights /> */}
        {/* <Analytics /> */}
        </body>
    </html>
  )
}
